// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfcyvnxdzirusatkcpem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmY3l2bnhkemlydXNhdGtjcGVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzEyMTUsImV4cCI6MjA1OTcwNzIxNX0.yY1kvuGoarU6AirsUJ8VAAbY7fsEuNl6FvFEVEts_iQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);